shop/emilyproj/cartapp/urls.py
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove<int:product_id>/',views.full_remove,name='full_remove'),
]

shop/emilyproj/emilyapp/urls.py
from . import views
from django.urls import path

app_name = 'emilyapp'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetails,name='proCatDetails'),
]

shop/emilyproj/emilyproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('emilyapp.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cartapp.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

shop/emilyproj/searchapp/urls.py
from . import views
from django.urls import path

app_name = 'searchapp'

urlpatterns = [
    path('',views.SerachResult,name='SerachResult'),
]

shop/emilyproj/cartapp/models.py
from django.db import models
from emilyapp.models import Product ,Category

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table ='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

shop/emilyproj/emilyapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('emilyapp:product_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('emilyapp:proCatDetails',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

shop/emilyproj/searchapp/models.py
from django.db import models

# Create your models here.

shop/emilyproj/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from emilyapp.models import Product
from .models import Cart , CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),

    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()

    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter = cart_item.quantity

    except ObjectDoesNotExist:
        pass

    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()

    else:
        cart_item.delete()

    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()

    return redirect('cart:cart_detail')

shop/emilyproj/emilyapp/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from . models import Category , Product
from django.core.paginator import Paginator , InvalidPage , EmptyPage

# Create your views here.

#
# def emily(request):
#     return HttpResponse('hai')

def allProdCat(request,c_slug=None):
    c_page = None
    products_list =None
    if c_slug!=None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page,available=True)

    else:
        products_list = Product.objects.all().filter(available=True)

    paginator = Paginator(products_list,6)
    try:
        page = int(request.GET.get('page','1'))

    except:
        page = 1

    try:
        products = paginator.page(page)

    except(EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def proDetails(request,c_slug,product_slug):
    try:
        products = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':products})

shop/emilyproj/searchapp/views.py
from django.shortcuts import render
from emilyapp.models import Product
from django.db.models import Q


# Create your views here.

def SerachResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))

        return render(request,'search.html',{'query':query,'products':products})

shop/emilyproj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
<!--    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300&display=swap" rel="stylesheet">-->
<!--    <link href="https://fonts.googleapis.com/css2?family=Comforter&display=swap" rel="stylesheet">-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}
    {% endblock %}
    </title>
    <style>
        body {
    background-color: rgba(163, 150, 46, 0.254);
}
    </style>
</head>
<body>

<div class="container">

    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

</div>

{% include 'footer.html' %}

    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>

shop/emilyproj/templates/cart.html
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}
    This is the cart page that you wanted to be purchased.
{% endblock %}

{% block title %}
    CART
{% endblock %}

{% block content %}

    {% if not cart_items %}

    <div>
        <div class="text-center">  <br>

            <h1 class="text-center my_title"> You'r Shopping cart is empty. </h1>
            <br>
            <p class="text-center">
                Please click
                <a href="{% url 'emilyapp:allProdCat' %}"><b>HERE</b></a>
                to continue shopping.
            </p>

        </div>
    </div>

    {% else %}

    <div>
        <div class="text-center">

            <h1 class="text-center my_title" style="padding-top: 10px;">You'r shopping cart.</h1>

            <br>

        </div>
    </div>

    <div class="row mx-auto  p-3 shadow">
        <div class="col-12 col-sm-12 col-lg-6 text-center">

            <table class="my_custom_table">
            <thead class="my_custom_thead">

            <tr>
                <th colspan="5">You'r Items.</th>
            </tr>

            </thead>
                <tbody>

                {% for cart_item in cart_items %}
                <tr>

                    <td>
                        <a href="cart_item.product.get_absolute_url">
                            <img src="{{ cart_item.product.image.url }}" alt="Product Image-Should be here." style="width:100px;height:100px;" class="float-left rounded custom_image">
                        </a>
                    </td>


                    <td class="text-left">
                        <div>
                        {{ cart_item.product.name }} <br>
                        SKU : {{ cart_item.product.id }} <br>
                        PRICE : ${{ cart_item.product.price }} <br>
                        QTY : {{ cart_item.quantity }} x ${{ cart_item }}
                        </div>
                    </td>

                    <td>
                        ${{ cart_item.sub_total }}
                    </td>

                    {% if cart_item.quantity < cart_item.product.stock %}

                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"> </i> </a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa fa-minus custom_icon"> </i> </a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa fa-trash custom_icon"> </i> </a>
                    </td>

                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-minus-square-o custom_icon"></i> </a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-minus-trash-o custom_icon"></i> </a>
                    </td>

                    {% endif %}

                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div>
            <table class="table my_custom_table">

                <thead class="my_custom_thead">

                <tr>

                    <th>Check Out.</th>

                </tr>

                </thead>

                <tbody>
                <tr>

                    <td>
                        Please review you'r shopping cart items before poceding with the order payments.
                    </td>

                </tr>
                <tr>
                    <td class="text-left"> You'r total :- ${{ total }}</td>
                </tr>
                </tbody>

            </table>

            <div class="mx-auto">

                <a href="{% url 'emilyapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_buttom">Continue Shopping</a>

            </div>

        </div>
        </div>
    </div>
    {% endif %}


{% endblock %}

shop/emilyproj/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcom to You by You'r needs ....

    {% endif %}
{% endblock %}

<!-------------------------------------------->

{% block title %}
    {% if category %}
        {{ category.name }} --- You

    {% else %}
        See Our New Collections

    {% endif %}
{% endblock %}

<!------------------------------------------>

{% block content %}

    {% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx_auto">
            <p>
                <a href="{% url 'emilyapp:allProdCat' %}">Our Products.</a>
            </p>
            </div>
        </div>
    </div>
    {% endif %}

    <div class="mx_auto">
        {% if category %}
        <img class="my_image" src="{{ category.image.url}}" alt="{{category.name}}">
    </div>
<br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p>{{category.description}}</p>
    </div>

        {% else %}
        <div>
            <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products" height="500px" width="100%">
        </div>
        <br>
        <div>
            <h1 class="text-center my_title">
                Our FORMAL'S Collections
            </h1>
            <p class="text-justify">
                Formal wear and formal dress are general terms for clothing suitable for formal social events, such as a wedding, formal garden party or dinner, débutante cotillion, dance, or race. ...
                A dress code is a set of rules governing a certain combination of clothing; some examples are black tie and morning dress.
                In western countries, a "formal" or white tie dress code typically means tailcoats for men and full-length evening dresses with opera-length gloves for women.
                A most formal dress for women are full-length ball or evening gowns with evening gloves.
                Formal skirts emanate class and confidence and can be easily paired with solid full-sleeved shirts as well as blouses.
                Skirts make a great formal wear for office and high-functioning corporate events.
                It's advisable to choose skirts that are knee length or below the knee for a formal look.
                The tuxedo is the heart of formal dress. For the DRESSIEST of occasions, bow tie is a must – a tailed jacket, white shirt and white bow tie.
                For slightly less starched occasions, black tie is the order of the day – a tailless jacket, black cummerbund or waistcoat, and a black bow tie.
            </p>
        </div>
        {% endif %}


    <div class="container">

        <div class="row mx-auto">

            {% for product in products.object_list %}

            <div class="my_bottom_marging col-9 col-sm-12 col-md-4 xol-md-4">

                <div class="card text-center p-3 shadow" style="min-width: 18erm;">

                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>

               <div class="card-body">

                   <h4>{{product.name}}</h4>

                   <p>{{product.price}}</p>

               </div>

                </div>

            </div>

            {% endfor %}

        </div>

        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">

                {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                {% endfor %}

            </div>

            {% endif %}

        </div>
        <br>

    </div>



{% endblock %}

shop/emilyproj/templates/footer.html
<div class="site_footer">
<div class="footer navbar-fixed-bottom my_footer">

    <p class="text-center" style="background-color: gray;">
        &copy; You tech pvt ltd All Rights Reserved....
    </p>
</div>
</div>

shop/emilyproj/templates/header.html
{% load static %}
<div class="logo">
<header>
  <center>
      <a href="{% url 'emilyapp:allProdCat' %}"> <img src="{% static 'img/logo.png' %}" alt="logo" height="100ph" width="100ph"> </a>
  </center>
</header>
    </div>


<!-- class="p-3 shadow"-->

shop/emilyproj/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light p-3 shadow bar">

  <div class="container-fluid">

<!--    <a class="navbar-brand" href="#">Navbar</a>-->

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

          <span class="navbar-toggler-icon"></span>

    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

<!--        <li class="nav-item">-->
<!--          <a class="nav-link active" aria-current="page" href="#">Home</a>-->
<!--        </li>-->

        <li class="nav-item">

          <a class="nav-link" href="{% url 'emilyapp:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'emilyapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'emilyapp:allProdCat' %}">Our Products</a></li>
            {% for cats in links %}
            <li><a class="dropdown-item" href="{{cats.get_url}}">{{cats.name}}</a></li>
            {% endfor %}
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
          </ul>
        </li>
          {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}" > <i class="fa fa-shopping-cart" aria-disabled="true" ></i>( {{ item_count }} )</a>
        </li>
          {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchapp:SerachResult' %}" method="get">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

<!--<nav>-->
<!--  <ul>-->
<!--    <li><a href=""></a></li>-->


<!--    <li>-->
<!--      <a href=""></a>-->
<!--    </li>-->


<!--    <li></li>-->
<!--  </ul>-->
<!--</nav>-->

shop/emilyproj/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription|truncatewords:155 %}

  {{ product.description }}

{% endblock %}

{% block title %}

  {{ product.name }}

{% endblock %}
{% block content %}
  <div class="row my_prod_row_class">
    <div class="mx_auto">

      <p><a href="{% url 'emilyapp:allProdCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a> | {{ product.name }}</p>

    </div>


  <div class="container">

  <br>

  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">

      <div style="min-width: 15rem;">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" height="250px" width="250px" class=" p-3 shadow">
      </div>

    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
      <div>
        <h1 class="my_prod_title">{{ product.name }}</h1>
        <p>${{ product.price }}</p>

        <p class="my_title">Product Description</p>
        <p class="text-justify my_prod_text">{{ product.description }}</p>

        {% if product.stock <= 0 %}

        <p><b> Not Available At This Moment. </b></p>

        {% else %}

        <div class="my_btn">

        <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a>

        {% endif %}

          </div>

      </div>
    </div>
  </div>
  </div>
  </div>
{% endblock %}

shop/emilyproj/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have varitey of poducts .
{% endblock %}
{% block title %}
    Search.
{% endblock %}
{% block content %}
    <div>
        <p class="text-center my_search_text">
            You have searched for : <b>{{query}}</b>
        </p>
    </div>
    <div class="container">

        <div class="row mx-auto">

            {% for product in products %}

            <div class="my_bottom_marging col-9 col-sm-12 col-md-4 xol-md-4">

                <div class="card text-center p-3 shadow" style="min-width: 18erm;">

                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>

               <div class="card-body">

                   <h4>{{product.name}}</h4>

                   <p>{{product.price}}</p>

               </div>

                </div>

            </div>

            {% empty %}
            <div class="row mx_aotu">
                <p class="text-cente my_search_text">
                    You Searched For
                </p>
            </div>
        </div>
    </div>

            {% endfor %}
{% endblock %}